booker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booker_app/', include('booker_app.urls'))
]

booker_app/urls.py
from django.urls import path
from booker_app.views import (
    BookView, BookFormView, BookDetailsView, BookDelete, BookListJsonView,
    ImportBookView
)

urlpatterns = [
    path('book_list/', BookView.as_view(), name='book_list'),
    path('book_list_json/', BookListJsonView.as_view(), name='book_list_json'),
    path(
        'book_details/<int:book_id>/',
        BookDetailsView.as_view(),
        name='book_details'
    ),
    path('add_book/', BookFormView.as_view(), name='add_book'),
    path(
        'book_details/<int:id>/delete_book/',
        BookDelete.as_view(),
        name='delete_book'
    ),
    path('import_book/', ImportBookView.as_view(), name='import_book'),
]

booker_app/forms.py
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError

from booker_app.models import Book, Identifier
from booker.settings import MAX_STR_LEN


class BookForm(forms.Form):
    authors = forms.CharField(
        max_length=MAX_STR_LEN,
        label='Authors',
        widget=forms.TextInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )
    title = forms.CharField(
        max_length=MAX_STR_LEN,
        label='Title',
        widget=forms.TextInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )
    pub_date = forms.CharField(
        required=False,
        label='Publication date (YYYY-MM-DD)',
        widget=forms.TextInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )
    page_count = forms.IntegerField(
        label='Page count',
        required=False,
        widget=forms.NumberInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )
    language = forms.CharField(
        max_length=2,
        help_text='2 letters format, eg. "en", "pl"',
        label='Language',
        widget=forms.TextInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )
    cover_image_adress = forms.URLField(
        max_length=MAX_STR_LEN,
        required=False,
        label='Cover image adress',
        widget=forms.TextInput(
                 attrs={'size':'30', 'class':'inputText'}
        )
    )

    def clean(self):
        cleaned = self.cleaned_data
        check_date_pub = cleaned.get('pub_date')
        if len(check_date_pub) < 1:
            check_date_pub = None
        elif len(check_date_pub) == 4:
            check_date_pub += '-01-01'
            check_date_pub = datetime.strptime(check_date_pub, '%Y-%m-%d')
        elif len(check_date_pub) > 4 and len(check_date_pub) < 8:
            check_date_pub += '-01'
            check_date_pub = datetime.strptime(check_date_pub, '%Y-%m-%d')

        cleaned = {
            'authors': cleaned.get('authors'),
            'title': cleaned.get('title'),
            'pub_date': check_date_pub,
            'page_count': cleaned.get('page_count'),
            'language': cleaned.get('language'),
            'cover_image_adress': cleaned.get('cover_image_adress')
        }
        return cleaned


class BookFormEdit(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookFormEdit, self).__init__(*args, **kwargs)
        self.fields['authors'].widget.attrs['size'] = 30
        self.fields['title'].widget.attrs['size'] = 30
        self.fields['pub_date'].widget.attrs['size'] = 30
        self.fields['language'].widget.attrs['size'] = 30
        self.fields['page_count'].widget.attrs['size'] = 30
        self.fields['cover_image_adress'].widget.attrs['size'] = 30

    class Meta:
        model = Book
        fields = [
            'authors',
            'title',
            'pub_date',
            'language',
            'page_count',
            'cover_image_adress'
        ]


class IdentifierForm(forms.Form):
    ISBN_10 = forms.CharField(
        max_length=MAX_STR_LEN,
        required=False,
        widget=forms.TextInput(
            attrs={'size':'30', 'class':'inputText'}
        )
    )
    ISBN_13 = forms.CharField(
        max_length=MAX_STR_LEN,
        required=False,
        widget=forms.TextInput(
            attrs={'size':'30', 'class':'inputText'}
        )
    )
    ISSN = forms.CharField(
        max_length=MAX_STR_LEN,
        required=False,
        widget=forms.TextInput(
            attrs={'size':'30', 'class':'inputText'}
        )
    )
    OTHER = forms.CharField(
        max_length=MAX_STR_LEN,
        required=False,
        widget=forms.TextInput(
            attrs={'size':'30', 'class':'inputText'}
        )
    )


class SearchBookForm(forms.Form):
    search_field = forms.CharField(max_length=MAX_STR_LEN, label='Search')


class ImportBookForm(forms.Form):
    # Special keywords user can specify in the search terms to search
    # in particular fields. I chose only these field which can be saved in db.
    SEARCH_KEYWORDS = [
        ('inauthor', 'author'),
        ('intitle', 'title'),
        ('isbn', 'isbn'),
        ('lccn', 'lccn'),
        ('oclc', 'oclc')
    ]
    search_authors = forms.CharField(
        max_length=MAX_STR_LEN, label='Search in authors', required=False)
    search_title = forms.CharField(
        max_length=MAX_STR_LEN, label='Search in title', required=False)
    search_isbn = forms.CharField(
        max_length=MAX_STR_LEN, label='Search in isbn', required=False)
    search_lccn = forms.CharField(
        max_length=MAX_STR_LEN, label='Search in lccn', required=False)
    search_oclc = forms.CharField(
        max_length=MAX_STR_LEN, label='Search in oclc', required=False)

    def clean(self):
        cleaned = self.cleaned_data
        counter = 0
        search_authors = cleaned.get("search_authors")
        search_title = cleaned.get("search_title")
        search_isbn = cleaned.get("search_isbn")
        search_lccn = cleaned.get("search_lccn")
        search_oclc = cleaned.get("search_oclc")
        keywords_fields = [
            search_authors,
            search_title,
            search_isbn,
            search_lccn,
            search_oclc
        ]
        for keyword in keywords_fields:
            if keyword:
                counter += 1
        if counter < 1:
            # Error raises if no field was filled in
            raise ValidationError("Fill in at least one field to import books")

        return cleaned

booker_app/views.py
import json
import requests
from datetime import datetime

from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.http import (
    HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
)
from django.urls import reverse_lazy
from django.views import View

from booker_app.forms import (BookForm, IdentifierForm, SearchBookForm,
    ImportBookForm, BookFormEdit
)
from booker_app.models import Book, Identifier


class BookView(View):
    def get(self, request):
        book_list = Book.objects.all()
        form = SearchBookForm()
        context = {'book_list': book_list, 'form': form}
        return render(request, 'book_list.html', context)

    def post(self, request, *args, **kwargs):
        form = SearchBookForm(request.POST)
        if not form.is_valid():  # TODO fix redirect
            return redirect('book_list')
        search_phrase = form.cleaned_data['search_field']
        search_result = Book.objects.filter(
            Q(authors__icontains=search_phrase) |
            Q(title__icontains=search_phrase) |
            Q(language__icontains=search_phrase) |
            Q(pub_date__icontains=search_phrase)
        )

        context = {'book_list': search_result}
        return render(request, 'book_list.html', context)


class BookListJsonView(View):
    def get(self, request):
        """Search keyword should be passed through the URL as a querystring
        in the following format:
        ?authors=[AUTHORS]&title=[TITLE]&language=[LANGUAGE]&pub_date=[YYYY-MM-DD]
        """
        authors = request.GET.get('authors', '')
        title = request.GET.get('title', '')
        language = request.GET.get('language', '')
        pub_date = request.GET.get('pub_date', '')
        search_result = list(Book.objects.filter(
            authors__icontains=authors,
            title__icontains=title,
            language__icontains=language,
            pub_date__icontains=pub_date
        ).values())

        return JsonResponse(search_result, safe=False)


class BookDetailsView(View):
    def get(self, request, book_id):
        book = Book.objects.get(id=book_id)
        if not book:
            not_found_msg = 'Book not found'
            return render(request, 'book_details.html', not_found_msg)
        form_book = BookFormEdit(
            initial={
                'authors': book.authors,
                'title': book.title,
                'pub_date': book.pub_date,
                'page_count': book.page_count,
                'language': book.language,
                'cover_image_adress': book.cover_image_adress
            }
        )
        identifiers = Identifier.objects.filter(book_id=book.id).all()
        initial_values = {
            ident.type: ident.value for ident in identifiers}
        form_ident = IdentifierForm(initial=initial_values)

        context = {'form_book': form_book, 'form_ident': form_ident}
        return render(request, 'book_details.html', context)

    def post(self, request, book_id):
        book = Book.objects.get(id=book_id)
        if not book:
            not_found_msg = 'Book not found'
            return render(
                request,
                'book_details.html',
                {'not_found_msg':not_found_msg}
            )

        form_book = BookFormEdit(
            request.POST,
            initial={
                'authors': book.authors,
                'title': book.title,
                'pub_date': book.pub_date,
                'page_count': book.page_count,
                'language': book.language,
                'cover_image_adress': book.cover_image_adress
            },
            instance=book
        )

        identifiers = Identifier.objects.filter(book_id=book.id).all()
        ident_types_in_book = [ident.type for ident in identifiers]
        form_ident = IdentifierForm(request.POST)

        if form_book.is_valid():
            form_book.save(commit=False)

            if form_ident.is_valid():
                for ident_type in Identifier.IDENTIFIER_TYPES:
                    ident_type = ident_type[0]  # Pick a value from the tuple
                    if form_ident.cleaned_data[ident_type]:
                        # check if ident value exists in other book.
                        ident_exist_in_other_book = Identifier.objects.filter(
                            type=ident_type,
                            value=form_ident.cleaned_data[ident_type]
                        ).first()
                        if (ident_exist_in_other_book and
                            ident_exist_in_other_book.book_id != book.id):
                            error_msg = "Book with this identifier already exists."
                            return render(
                                request,
                                'book_list.html',
                                {'error_msg': error_msg}
                            )
                        form_book.save()
                        if ident_type in ident_types_in_book:
                            ident_to_update = Identifier.objects.filter(
                                book_id=book.id, type=ident_type
                            ).first()
                            ident_to_update.type=ident_type
                            ident_to_update.value=form_ident.cleaned_data[ident_type]
                            ident_to_update.book=book
                            ident_to_update.save()
                        else:
                            Identifier(
                            type=ident_type,
                            value=form_ident.cleaned_data[ident_value],
                            book=book
                            ).save()
                        success_msg = 'Book updated successfully'
                        context = {
                            'form_book': form_book,
                            'form_ident': form_ident,
                            'success_msg': success_msg
                        }
                        return render(request, 'book_details.html', context)
            else:
                error_msg = "Updating failed. Invalid indentifier."
                context = {'error_msg': error_msg}
                return render(request, 'book_details.html', context)

        else:
            success_msg = 'Book updated successfully'
            context = {
                'form_book': form_book,
                'form_ident': form_ident,
                'success_msg': success_msg
            }
            return render(request, 'book_details.html', context)


class BookFormView(View):
    def get(self, request):
        form_book = BookForm()
        form_ident = IdentifierForm()
        return render(
            request,
            'add_book.html',
            {'form_book': form_book, 'form_ident': form_ident}
        )

    def post(self, request):
        form_book = BookForm(request.POST)
        form_ident = IdentifierForm(request.POST)

        book_exists = None
        ident_instances = []
        if form_ident.is_valid():
            for ident_type in Identifier.IDENTIFIER_TYPES:
                ident_type = ident_type[0]  # Pick a value from the tuple
                value = form_ident.cleaned_data[ident_type]
                if value:
                    ident = Identifier.objects.filter(
                        type=ident_type,
                        value=value
                    ).first()
                    if ident:
                        book_exists = True
                        error_msg = (
                            f'Book with {ident_type}: {value} already exists.'
                        )
                        break
                    else:
                        ident_instances.append(Identifier(
                            type=ident_type,
                            value=value
                        ))

        if book_exists:
            return render(
                request,
                'add_book.html',
                {
                    'form_book': form_book,
                    'form_ident': form_ident,
                    'error_msg': error_msg
                }
            )

        if form_book.is_valid():
            authors=form_book.cleaned_data['authors']
            title=form_book.cleaned_data['title']
            pub_date=form_book.cleaned_data['pub_date']
            page_count=form_book.cleaned_data['page_count']
            language=form_book.cleaned_data['language']
            cover_image_adress=form_book.cleaned_data['cover_image_adress']

            # If no idents exist we don't want to duplicate the book
            if not ident_instances and self.check_if_book_exists(
                authors,
                title,
                pub_date,
                page_count,
                language,
                cover_image_adress):

                error_msg = f'{title} by {authors} already exists.'
                return render(
                    request,
                    'add_book.html',
                    {
                        'form_book': form_book,
                        'form_ident': form_ident,
                        'msg': error_msg
                    }
                )

            new_book = Book(
                authors=form_book.cleaned_data['authors'],
                title=form_book.cleaned_data['title'],
                pub_date=form_book.cleaned_data['pub_date'],
                page_count=form_book.cleaned_data['page_count'],
                language=form_book.cleaned_data['language'],
                cover_image_adress=form_book.cleaned_data['cover_image_adress']
            )
            new_book.save()
            for ident in ident_instances:
                ident.book = new_book
                ident.save()

            return redirect('book_list')


    def check_if_book_exists(
        self,
        authors,
        title,
        pub_date,
        page_count,

booker_app/templates/add_book.html
{% include 'partials/header.html' %}
{% load static %}
{% include 'partials/header.html' %}
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/booker_app/book_list">Booker App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/booker_app/add_book">Add a book</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/import_book">Import a book</a>
      </li>
    </ul>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
    <form action="{% url 'add_book' %}" method="post">
        {% csrf_token %}
        <h2>Add book</h2>
        <hr>
            {% if error_msg %}
                <p class="error_msg">{{ error_msg }}</p>
            {% endif %}
        <div class="container">
            <div class="row justify-content-md-left">
              <div class="col-3 col-sm-2 my-2">Title</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.title }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Authors</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.authors }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Published date</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.pub_date }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Language</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.language }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Page count</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.page_count }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Cover adress image</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.cover_image_adress }}</div>
              <div class="w-100"></div>

              <div class="col-3 col-sm-2 my-2">ISBN 10</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISBN_10 }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">ISBN 13</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISBN_13 }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">ISSN</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISSN }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">OTHER</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.OTHER }}</div>
              <div class="w-100"></div>

              <div class="col-3 col-sm-2 my-2">
                  <button type="submit" class="save btn btn-info">
                      Add book
                  </button>
             </div>
        </div>
    </div>
    </form>
  </div>
</main>

{% include 'partials/footer.html' %}

booker_app/templates/book_details.html
{% include 'partials/header.html' %}
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/booker_app/book_list">Booker App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/add_book">Add a book</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/import_book">Import a book</a>
      </li>
    </ul>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
      <h2>Book details</h2>
      <hr>
        {% if not_found_msg %}
            <p class="error_msg">{{ not_found_msg }}</p>
        {% endif %}
        {% if success_msg %}
            <p class="success_msg">{{ success_msg }}</p>
        {% endif %}

    {% if form_book %}
        <form action='.' method="post">
            {% csrf_token %}
        <div class="container">
            <div class="row justify-content-md-left">
              <div class="col-3 col-sm-2 my-2">Title</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.title }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Authors</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.authors }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Published date</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.pub_date }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Language</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.language }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Page count</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.page_count }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">Cover adress image</div>
              <div class="col-3 col-sm-2 my-2">{{ form_book.cover_image_adress }}</div>
              <div class="w-100"></div>

              <div class="col-3 col-sm-2 my-2">ISBN 10</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISBN_10 }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">ISBN 13</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISBN_13 }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">ISSN</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.ISSN }}</div>
              <div class="w-100"></div>
              <div class="col-3 col-sm-2 my-2">OTHER</div>
              <div class="col-3 col-sm-2 my-2">{{ form_ident.OTHER }}</div>
              <div class="w-100"></div>

             <hr>
             <div class="col-3 col-sm-2 my-2">
                 <button type="submit" class="save btn btn-info">
                     Update book
                 </button>
            </div>
           </div>
        </div>
        </form>
        {% endif %}
            <div class="col-3 col-sm-2 my-2">
                <form action='delete_book/' method="post">
                    {% csrf_token %}
                    <button type="submit" class="save btn btn-warning">Delete book</button>
                </form>
           </div>
  </div>

</main>
{% include 'partials/footer.html' %}

booker_app/templates/book_list.html
{% include 'partials/header.html' %}
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/booker_app/book_list">Booker App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/add_book">Add a book</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/import_book">Import a book</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0" action="." method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" id="id_search_field" name="search_field" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
    <h2>Book list</h2>
    <hr>
        {% if error_msg %}
            <p class="error_msg">{{ error_msg }}</p>
        {% endif %}

        {% if success_msg %}
            <p class="success_msg">{{ success_msg }}</p>
        {% endif %}

    {% if book_list %}
    <div class="container">
        <div class="row justify-content-md-left">
        {% for book in book_list %}
          <div class="col-6 my-2">
                    Title: {{ book.title}},
                    <br>
                    Authors: {{ book.authors }},
                    <br>
                    Published date: {{ book.pub_date }},
                    <br>
                    Language: {{ book.language }},
                    <br>
                    Page count: {{ book.page_count }},
                    <br>
                    {% for ident in book.identifier_display %}
                    Identifier: {{ ident }},
                    {% endfor %}

                    <br><a class='details' href="/booker_app/book_details/{{ book.id }}">
                        Click to see details</a>
                    <hr>

            </div>
            <div class="col-6 my-2">
                {% if book.cover_image_adress %}
                <a href="{{ book.cover_image_adress }}">
                    <img src="{{ book.cover_image_adress }}"
                    alt="Book cover adress not available"">
                </a>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>

    {% endif %}

  </div>
</main>

{% include 'partials/footer.html' %}

booker_app/templates/book_list_bkup.html
{% include 'partials/header.html' %}
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/booker_app/book_list">Booker App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/add_book">Add a book</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/booker_app/import_book">Import a book</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0" action="." method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" id="id_search_field" name="search_field" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
    <h2>Book list</h2>
    <hr>
    {% if book_list %}
    <div class="container">
        <div class="row justify-content-md-left">
        <ol>
          <div class="col-8 my-2">
              {% for book in book_list %}
                <li>
                    Title: {{ book.title}},
                    <br>
                    Authors: {{ book.authors }},
                    <br>
                    Published date: {{ book.pub_date }},
                    <br>
                    Language: {{ book.language }},
                    <br>
                    Page count: {{ book.page_count }},
                    <br>
                        {% for ident in book.identifier_display %}
                        Identifier: {{ ident }},
                        {% endfor %}
                    <br>

                    {% if book.cover_image_adress %}
                    <div class='cover_image_adress'>
                    <a href="{{ book.cover_image_adress }}">
                        <img src="{{ book.cover_image_adress }}"
                        alt="Book cover adress not available"">
                    </a>
                    </div>
                    {% endif %}

                    <a class='details' href="/booker_app/book_details/{{ book.id }}">
                        Click to see details</a>
                </li>
                <hr>
                {% endfor %}
                </div>
            </ol>
            </div>
        </div>
    </div>
    {% else %}
        {% if error_msg %}
            {{ error_msg }}
         {% elif success_msg %}
            {{ success_msg }}
        {% else %}
        <p>No books found.</p>
        {% endif %}
    {% endif %}

  </div>
</main>

{% include 'partials/footer.html' %}